stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: blueforest/mq-upsert-delete:1.0.2
      pushRemote: true
      registry: index.docker.io
timeout: 60
